---
# Site settings
title: VERITAStrophe
timezone: America/Los_Angeles
collections:
  posts:
    title: Posts
    output: true
  uploads:
    title: Uploads
    output: true
email: beastie@veritastrophe.com
author: Ellie Evans
description: Just a middle-aged teenager.
baseurl: ''
url: https://veristastrophe.com
favicon: favicon.ico
disclaimer: Opinions expressed on this site are my own and do not reflect the views of my employer.

# Keep files in _site
destination: _site
keep_files: 
  - assets/img
  - feed.xml
  - favicon.ico
  - robots.txt

# Jekyll theme and plugins
theme: minima
plugins:
- jekyll-feed
- jekyll-seo-tag

# Blog settings
show_excerpts: true

# Social media usernames
twitter_username: ellieAPI
github_username: evansekeful
spotify_username: 12458204
strava_username: evansekeful
facebook_username: placeholder
bluesky_username: placeholder
instagram_username: veristastrophe

