---
# Site settings
title: veristastrophe
timezone: UTC
collections:
  posts:
    title: Posts
    output: true
  uploads:
    title: Uploads
    output: true
email: beastie@veritastrophe.com
author: Ellie Evans
description: Just a middle-aged teenager.
baseurl: ''
url: https://veristastrophe.com
disclaimer: Opinions discussed on this site are my own.

# Keep files in _site
destination: _site
keep_files: 
  - assets/img

# Jekyll theme and plugins
theme: minima
plugins:
- jekyll-feed

# Social media usernames
twitter_username: ellieAPI
github_username: evansekeful
spotify_username: 12458204
strava_username: evansekeful
facebook_username: placeholder
bluesky_username: placeholder
instagram_username: veristastrophe

